do that for core too

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -73,11 +73,11 @@ jobs:
       #     --tmp=$(pwd)/tmp \
       #     --rootfs-size=8 \
       #     $(pwd)/home-${{matrix.arch}}
-      - name: Clean up after lorax
-        if: always()
-        run: |
-          sudo losetup -d /dev/loop0 2> /dev/null || true
-          sudo losetup -d /dev/loop1 2> /dev/null || true
+      # - name: Clean up after lorax
+      #   if: always()
+      #   run: |
+      #     sudo losetup -d /dev/loop0 2> /dev/null || true
+      #     sudo losetup -d /dev/loop1 2> /dev/null || true
       # - name: Upload Artifacts
       #   uses: actions/upload-artifact@v3.0.0
       #   with:
@@ -102,82 +102,82 @@ jobs:
         if: steps.cache.outputs.cache-hit != 'true'
       - run: ostree remote add --no-gpg-verify --force --repo repo tauOS https://repo.tauos.co/ostree tau/core/1/${{matrix.arch}}
       - run: ostree pull --repo repo --mirror tauOS tau/core/1/${{matrix.arch}}
-      - name: Prepare environment for lorax run
-        run: |
-          # We have to pre-create loop devices because they are not namespaced in kernel so
-          # podman can't access newly created ones. That caused failures of tests when runners
-          # were rebooted.
-          sudo mknod -m 0660 /dev/loop0 b 7 0  2> /dev/null || true
-          sudo mknod -m 0660 /dev/loop1 b 7 1  2> /dev/null || true
-      - run: |
-          lorax --product=tauOS \
-          --version=1 \
-          --release=1 \
-          --variant=core \
-          --source=https://kojipkgs.fedoraproject.org/compose/37/latest-Fedora-37/compose/Everything/${{matrix.arch}}/os/ \
-          --source=https://repos.fyralabs.com/tau1/ \
-          --source=https://repos.fyralabs.com/terra37/ \
-          --installpkgs=tau-logos \
-          --installpkgs=tau-release \
-          --installpkgs=tau-release-desktop \
-          --installpkgs=tau-repos \
-          --installpkgs=tau-gpg-keys \
-          --installpkgs=fedora-repos \
-          --installpkgs=tau-anaconda-profiles \
-          --installpkgs=tau-plymouth \
-          --installpkgs=tau-helium \
-          --installpkgs=tau-hydrogen \
-          --installpkgs=tau-manrope-fonts \
-          --volid=tauOS-Core-Installer \
-          --nomacboot \
-          --skip-branding \
-          --add-template=$(pwd)/lorax-configure-repo.tmpl \
-          --add-template=$(pwd)/lorax-embed-repo.tmpl \
-          --add-template-var=ostree_install_repo=file://$(pwd)/repo \
-          --add-template-var=ostree_update_repo=https://repo.tauos.co/ostree \
-          --add-template-var=ostree_osname=tauOS \
-          --add-template-var=ostree_oskey=tauOS-core \
-          --add-template-var=ostree_contenturl=https://repo.tauos.co/ostree \
-          --add-template-var=ostree_install_ref=tau/core/1/${{matrix.arch}} \
-          --add-template-var=ostree_update_ref=tau/core/1/${{matrix.arch}} \
-          --logfile=$(pwd)/lorax.log \
-          --tmp=$(pwd)/tmp \
-          --rootfs-size=8 \
-          $(pwd)/core-${{matrix.arch}}
-      - name: Upload Artifacts
-        uses: actions/upload-artifact@v3.0.0
-        with:
-          name: core-${{matrix.arch}}
-          path: core-${{matrix.arch}}/images/boot.iso
-  publish:
-    needs: [build-core, build-home]
-    runs-on: ubuntu-latest
-    container:
-      image: fedora:37
-      options: --privileged
-    steps:
-      - uses: actions/checkout@v3
-      - name: Download Artifacts
-        uses: actions/download-artifact@v3.0.0
-      - name: Prepare for Upload
-        run: |
-          mv home-x86_64/boot.iso home-x86_64.iso
-          mv core-x86_64/boot.iso core-x86_64.iso
-          mv home-aarch64/boot.iso home-aarch64.iso
-          mv core-aarch64/boot.iso core-aarch64.iso
-      - name: Create Draft Release
-        uses: ncipollo/release-action@v1.10.0
-        with:
-          name: "tauOS Latest ISO - ${{ github.run_id }}"
-          artifacts: "*.iso"
-          artifactErrorsFailBuild: true
-          tag: ${{ github.run_id }}
-          commit: main
-          draft: true
-      - name: Publish Draft Release
-        uses: ncipollo/release-action@v1.10.0
-        with:
-          tag: ${{ github.run_id }}
-          draft: false
-          allowUpdates: true
-          omitNameDuringUpdate: true
+      # - name: Prepare environment for lorax run
+      #   run: |
+      #     # We have to pre-create loop devices because they are not namespaced in kernel so
+      #     # podman can't access newly created ones. That caused failures of tests when runners
+      #     # were rebooted.
+      #     sudo mknod -m 0660 /dev/loop0 b 7 0  2> /dev/null || true
+      #     sudo mknod -m 0660 /dev/loop1 b 7 1  2> /dev/null || true
+      # - run: |
+      #     lorax --product=tauOS \
+      #     --version=1 \
+      #     --release=1 \
+      #     --variant=core \
+      #     --source=https://kojipkgs.fedoraproject.org/compose/37/latest-Fedora-37/compose/Everything/${{matrix.arch}}/os/ \
+      #     --source=https://repos.fyralabs.com/tau1/ \
+      #     --source=https://repos.fyralabs.com/terra37/ \
+      #     --installpkgs=tau-logos \
+      #     --installpkgs=tau-release \
+      #     --installpkgs=tau-release-desktop \
+      #     --installpkgs=tau-repos \
+      #     --installpkgs=tau-gpg-keys \
+      #     --installpkgs=fedora-repos \
+      #     --installpkgs=tau-anaconda-profiles \
+      #     --installpkgs=tau-plymouth \
+      #     --installpkgs=tau-helium \
+      #     --installpkgs=tau-hydrogen \
+      #     --installpkgs=tau-manrope-fonts \
+      #     --volid=tauOS-Core-Installer \
+      #     --nomacboot \
+      #     --skip-branding \
+      #     --add-template=$(pwd)/lorax-configure-repo.tmpl \
+      #     --add-template=$(pwd)/lorax-embed-repo.tmpl \
+      #     --add-template-var=ostree_install_repo=file://$(pwd)/repo \
+      #     --add-template-var=ostree_update_repo=https://repo.tauos.co/ostree \
+      #     --add-template-var=ostree_osname=tauOS \
+      #     --add-template-var=ostree_oskey=tauOS-core \
+      #     --add-template-var=ostree_contenturl=https://repo.tauos.co/ostree \
+      #     --add-template-var=ostree_install_ref=tau/core/1/${{matrix.arch}} \
+      #     --add-template-var=ostree_update_ref=tau/core/1/${{matrix.arch}} \
+      #     --logfile=$(pwd)/lorax.log \
+      #     --tmp=$(pwd)/tmp \
+      #     --rootfs-size=8 \
+      #     $(pwd)/core-${{matrix.arch}}
+      # - name: Upload Artifacts
+      #   uses: actions/upload-artifact@v3.0.0
+      #   with:
+      #     name: core-${{matrix.arch}}
+      #     path: core-${{matrix.arch}}/images/boot.iso
+  # publish:
+  #   needs: [build-core, build-home]
+  #   runs-on: ubuntu-latest
+  #   container:
+  #     image: fedora:37
+  #     options: --privileged
+  #   steps:
+  #     - uses: actions/checkout@v3
+  #     - name: Download Artifacts
+  #       uses: actions/download-artifact@v3.0.0
+  #     - name: Prepare for Upload
+  #       run: |
+  #         mv home-x86_64/boot.iso home-x86_64.iso
+  #         mv core-x86_64/boot.iso core-x86_64.iso
+  #         mv home-aarch64/boot.iso home-aarch64.iso
+  #         mv core-aarch64/boot.iso core-aarch64.iso
+  #     - name: Create Draft Release
+  #       uses: ncipollo/release-action@v1.10.0
+  #       with:
+  #         name: "tauOS Latest ISO - ${{ github.run_id }}"
+  #         artifacts: "*.iso"
+  #         artifactErrorsFailBuild: true
+  #         tag: ${{ github.run_id }}
+  #         commit: main
+  #         draft: true
+  #     - name: Publish Draft Release
+  #       uses: ncipollo/release-action@v1.10.0
+  #       with:
+  #         tag: ${{ github.run_id }}
+  #         draft: false
+  #         allowUpdates: true
+  #         omitNameDuringUpdate: true
