Use host devices

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -15,7 +15,7 @@ jobs:
     runs-on: ${{ matrix.arch == 'aarch64' && 'ARM64' || 'ubuntu-latest' }}
     container:
       image: ghcr.io/tau-os/builder:main
-      options: --privileged
+      options: --privileged -v /dev:/dev
     steps:
       - uses: actions/checkout@v3
       - uses: actions/cache@v3
@@ -27,13 +27,13 @@ jobs:
         if: steps.cache.outputs.cache-hit != 'true'
       - run: ostree remote add --no-gpg-verify --force --repo repo tauOS https://repo.tauos.co/ostree tau/home/1/${{matrix.arch}}
       - run: ostree pull --repo repo --mirror tauOS tau/home/1/${{matrix.arch}}
-      - name: Prepare environment for lorax run
-        run: |
-          # We have to pre-create loop devices because they are not namespaced in kernel so
-          # podman can't access newly created ones. That caused failures of tests when runners
-          # were rebooted.
-          sudo mknod -m 0660 /dev/loop0 b 7 0  2> /dev/null || true
-          sudo mknod -m 0660 /dev/loop1 b 7 1  2> /dev/null || true
+      # - name: Prepare environment for lorax run
+      #   run: |
+      #     # We have to pre-create loop devices because they are not namespaced in kernel so
+      #     # podman can't access newly created ones. That caused failures of tests when runners
+      #     # were rebooted.
+      #     sudo mknod -m 0660 /dev/loop0 b 7 0  2> /dev/null || true
+      #     sudo mknod -m 0660 /dev/loop1 b 7 1  2> /dev/null || true
       - run: |
           lorax --product=tauOS \
           --version=1 \
@@ -73,11 +73,11 @@ jobs:
           --tmp=$(pwd)/tmp \
           --rootfs-size=8 \
           $(pwd)/home-${{matrix.arch}}
-      - name: Clean up after lorax
-        if: always()
-        run: |
-          sudo losetup -d /dev/loop0 2> /dev/null || true
-          sudo losetup -d /dev/loop1 2> /dev/null || true
+      # - name: Clean up after lorax
+      #   if: always()
+      #   run: |
+      #     sudo losetup -d /dev/loop0 2> /dev/null || true
+      #     sudo losetup -d /dev/loop1 2> /dev/null || true
       - name: Upload Artifacts
         uses: actions/upload-artifact@v3.0.0
         with:
@@ -90,7 +90,7 @@ jobs:
     runs-on: ${{ matrix.arch == 'aarch64' && 'ARM64' || 'ubuntu-latest' }}
     container:
       image: ghcr.io/tau-os/builder:main
-      options: --privileged
+      options: --privileged -v /dev:/dev
     steps:
       - uses: actions/checkout@v3
       - uses: actions/cache@v3
@@ -102,13 +102,13 @@ jobs:
         if: steps.cache.outputs.cache-hit != 'true'
       - run: ostree remote add --no-gpg-verify --force --repo repo tauOS https://repo.tauos.co/ostree tau/core/1/${{matrix.arch}}
       - run: ostree pull --repo repo --mirror tauOS tau/core/1/${{matrix.arch}}
-      - name: Prepare environment for lorax run
-        run: |
-          # We have to pre-create loop devices because they are not namespaced in kernel so
-          # podman can't access newly created ones. That caused failures of tests when runners
-          # were rebooted.
-          sudo mknod -m 0660 /dev/loop0 b 7 0  2> /dev/null || true
-          sudo mknod -m 0660 /dev/loop1 b 7 1  2> /dev/null || true
+      # - name: Prepare environment for lorax run
+      #   run: |
+      #     # We have to pre-create loop devices because they are not namespaced in kernel so
+      #     # podman can't access newly created ones. That caused failures of tests when runners
+      #     # were rebooted.
+      #     sudo mknod -m 0660 /dev/loop0 b 7 0  2> /dev/null || true
+      #     sudo mknod -m 0660 /dev/loop1 b 7 1  2> /dev/null || true
       - run: |
           lorax --product=tauOS \
           --version=1 \
